[[tasks]]
type = "Fmu"
name = "FMU1"
path = "./target/debug/deps/libfmu_test.dylib"

[[tasks]]
type = "Gpio"
name = "GPIO_In"
pins = [1, 2, 3]

[[tasks]]
type = "Serial"
name = "Serial_Out"
port = "/dev/ttyUSB0"
baud_rate = 115200

[[tasks]]
type = "Udp"
name = "UDP_Comm"
local_addr = "127.0.0.1:8080"
remote_addr = "127.0.0.1:8081"

[[tasks]]
type = "Custom"
name = "MyCustomTask"

dependencies = []
