name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose

    - name: Run Integration Tests
      # We must use exactly one thread since tests bind to port 3030 for the web server
      run: cargo test --test integration_test --verbose -- --test-threads=1

  book:
    name: Build Book
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: 'latest'

    - name: Build Book
      run: mdbook build book/
